POST https://back-end-node-0q5p.onrender.com/videos
Content-Type: application/json

{
  "title": "Video Sobre PostgresSQL",
  "description": "Esse é o primeiro video",
  "duration": 180
}

###
GET https://back-end-node-0q5p.onrender.com/videos
//?search=SQL

###
PUT https://back-end-node-0q5p.onrender.com/videos/93df7122-5d13-4eb0-a944-1c801c54784e
Content-Type: application/json

{
  "title": "Video alterado com o put",
  "description": "Esse é o primeiro video",
  "duration": 180
}

###
DELETE https://back-end-node-0q5p.onrender.com/videos/b15de434-3a57-4ce5-bc16-629bf08d0331